config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  paginates_per 5
  validates :title, length: { maximum: 30 }, presence: true
  validate :validate_name_comma
  
  belongs_to :user

  private

  def validate_name_comma
    errors.add(:title, 'にカンマを含めることはできません')if title&.include?(',')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :email, uniqueness: { case_sensitive: false }
  end

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'taskm' && password == 'p1324'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @navitasks = Task.all.order(created_at: :desc).page(params[:page]).per(5)
    @taskcalendar = Task.all
    @q = Task.ransack(params[:q])
    @tasks = @q.result(distinct: true)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to task_path(@task), notice: "タスク「#{@task.title}」を登録しました。"
    else
      render :new
    end
    
  end

  def edit
    if @task.user_id != current_user.id
      redirect_to action: :index
    end
  end

  def update
    task = Task.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{task.title}」を更新しました。"
  end

  def destroy
    if @task.user_id == current_user.id
      @task.destroy
      redirect_to tasks_url, notice: "タスク「#{@task.title}」を削除しました。"
    else
      redirect_to tasks_url
    end
  end

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :start_date, :end_date).merge(user_id: current_user.id)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @tasks = current_user.tasks
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Task-M
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand 
      = link_to '/' do 
        = image_tag "task-m_icon.png", width: '150px', data: {"turbolinks"=>false}
      
      ul.navbar-nav.ml-auto
      - if user_signed_in?
        ul.navbar-nav.lists.ml-auto
          li.nav-item.list.nav-link
            = current_user.nickname
            ul.show-lists
              li= link_to 'マイページ',"/users/#{current_user.id}"
              li= link_to 'カレンダー',"/users/#{current_user.id}"
          li.nav-item = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'
      - else  
          li.nav-item= link_to 'ログイン', new_user_session_path, class: 'nav-link'
          li.nav-item= link_to '新規登録', new_user_registration_path, class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-success.time-limit= flash.notice
      = yield

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li= message
      
= form_with model: task, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'task_title'
  .form-group
    = f.label :description
    = f.text_area :description, row: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :start_date
    br
    = f.datetime_select :start_date, {}, class: 'form-control datetime-form'
  .form-group
    = f.label :end_date
    br
    = f.datetime_select :end_date, {}, class: 'form-control datetime-form'
  br
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/confirm_new.html.slim
h1 登録内容の確認

= form_with model: @task, local: true dp |f|
  table.table.table-hover 
    tbody 
      tr
        th= Task.human_attribute_name(:name)
        td= @task.name
        = f.hidden_field :name
      tr
        th= Task.human_attribute_name(:description)
        td= simple_format(@task.description)
        = f.hidden_field :description
  = f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3'
  = f.submit '登録', class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav_link'

= render partial: 'form', locals: {task: @task}

app/views/tasks/index.html.slim
h1 タスク一覧
.col-12.clearfix
  .float-right.btn-registration
    = link_to 'タスク登録', new_task_path, class: 'btn btn-primary btn-lg mb-3 btn-registration'

.col-12.clearfix
  = search_form_for @q, class: 'mb-5' do |f|
    .form-group.row 
      = f.label :title_cont, '名称', class: 'col-sm-2 col-form-label'
      .col-sm-10 
        = f.search_field :title_cont, class: 'form-control'
    .form-group.row 
      = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
      .col-sm-10 
        = f.search_field :created_at_gteq, class: 'form-control'
    .form-group 
        = f.submit class: 'btn btn-outline-primary'

= paginate @navitasks

table.table.table-hover
  thead.thead-default
    tr
      th= Task.human_attribute_name(:title)
      th= Task.human_attribute_name(:created_at)
      th= Task.human_attribute_name(:start_date)
      th= Task.human_attribute_name(:end_date)
      th
  tbody
    - @tasks.each do |task|
      tr
        td= link_to task.title, task_path(task)
        td= task.created_at.to_s(:datetime_jp)
        td= task.start_date.to_s(:datetime_jp)
        td= task.end_date.to_s(:datetime_jp)
        th
          .btn class="btn-primary mr-3" 
            = link_to edit_task_path(task) do 
              .icalss.far.fa-edit.fa-lg.fa-fw 
              |編集
          .btn class="btn-danger mr-3" 
            = link_to task, method: :delete, data: { confirm: "タスク「#{task.title}」を削除します。よろしいですか？"} do
              .iclass.fas.fa-trash-restore.fa-lg.fa-fw
              |削除

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav_link'

= render partial: 'form', locals: {task: @task}

app/views/tasks/show.html.slim
h1 タスクの詳細
  
.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.user.nickname
    tr
      th= Task.human_attribute_name(:title)
      td= @task.title
    tr
      th= Task.human_attribute_name(:description)
      td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= Task.human_attribute_name(:start_date)
      td= @task.start_date.to_s(:datetime_jp)
    tr
      th= Task.human_attribute_name(:end_date)
      td= @task.end_date.to_s(:datetime_jp)
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at.to_s(:datetime_jp)
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at.to_s(:datetime_jp)
    
= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.title}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/users/show.html.slim
h1 カレンダー

.col-12.clearfix
  .float-right.btn-registration
    = link_to 'タスク登録', new_task_path, class: 'btn btn-primary btn-lg mb-3 btn-registration' 

.container
  #calendar